Fix : httpx.Client removed argument "proxies"
TypeError: Client.__init__() got an unexpected keyword argument 'proxies'
---.
In httpx==0.28.0 version, the following error occurred
For an immediate workaround, specifying a version lower than 0.28.0 as the required version should fix it.